language: go
go:
- 1.x
before_install:
- go get -u golang.org/x/lint/golint github.com/stretchr/testify/assert
before_script:
- go get -d ./...
script:
- "./scripts/licensecheck.sh"
- go build ./...
- "./scripts/golint.sh"
- go vet ./...
- go test -v ./...
